### PR TITLE
Remove tank room cutscene. Fixes #170

### LINKED ISSUE #170: Remove cutscene from Hanubia - Tank Room
The cutscene that plays when entering this room repositions Samus to the bottom left door. This could cause issues with random start/door lock rando and should be removed if possible.

https://user-images.githubusercontent.com/38679103/203588053-ea369954-7229-42fe-9661-bd50fe5b6d12.mp4

### PR DESCRIPTION
**Pull request by ThanatosGit**
This is a simple fix to disable the hanubia cutscene for the tank room.

Should this maybe only be done if the upper door to the tank room was randomized?

### CODE REVIEW

**Comment by XenoWars** [comment]
"Should this maybe only be done if the upper door to the tank room was randomized?"

And then what happens if you start in the Central Unit? Just dont care about that situation? The item in that room could be wave beam, but then the cutscene reposition would softlock you. Really rare case, but a possible case.

**Comment by dyceron** [comment]
No reason to have the cutscene be active sometimes. It adds nothing to the randomizer.

**Comment by ThanatosGit** [comment]
> And then what happens if you start in the Central Unit? Just dont care about that situation? The item in that room could be wave beam, but then the cutscene reposition would softlock you. Really rare case, but a possible case.

Don't know what you mean. Central Unit is not a valid starting point in hanubia. Orange EMMI Introduction is valid but you are completly stuck there because red chozo does not appear. I guess the door is open(able) when it's randomized but that's another special case like "Orange EMMI Introduction as starting point is only solvable if door get's randomized." 
EMMI Zone Exit West is possible.

Nevertheless, the trigger for the cutscene is entering the tank room from the left and not from the right.

It's only a question of "how vanilla" should the game stay. As much as possible or don't care.

**Comment by dyceron** [comment]
> It's only a question of "how vanilla" should the game stay. As much as possible or don't care.

There are already plenty of options that make it less vanilla. One cutscene being removed changes nothing and is a QoL.

**Comment by duncathan** [comment]
agreed. no need for it to be an option

**Pull request merged**
