### PR TITLE
Add custom spawn points at arbitrary locations

### PR DESCRIPTION
**Pull request by ThanatosGit**
Allow to define something like
```
    "new_spawn_points": [
        {
            "new_actor": {
                "actor": "MY_CUSTOM_SP",
                "scenario": "s010_cave"
            },
            "location": {
                "x": -24667.00,
                "y": -1800.00,
                "z": 0.0
            }
        }
    ],
```
in patcher.json. You can use these spawn points as starting locations in the near future (after merging rdv stuff and create it properly from there) or in the very far to "never happen" future as destinations for elevator/transport/shuttles etc.

### CODE REVIEW

**Comment by henriquegemignani** [comment]
What about the camera groups and/or layers? Is something needed to handle these?

**Comment by ThanatosGit** [comment]
Sorry to answer with a counterquestion: In what situtations this could be relevant? I'm not really familiar with camera "stuff" and have no idea how this comes into play.

I could just quickly tell what I did so far: Used this PR and tested some locations via odr directly. Later, I took my rdv pr https://github.com/randovania/randovania/pull/4016, added another small patch to be able to create the above new fields for odr from rdv, created some start nodes within the database without anything extra besides the position, used random start and created some seeds. Looks like this with a start point node in the db in ferenia purple emmi introduction room. (using warp to start. looks the same for a new game)

https://user-images.githubusercontent.com/117127188/210712234-f2969a60-bec8-47a1-98af-fbc3b3ca20f4.mp4

```
{
    ...
    "starting_location": {
        "scenario": "s070_basesanc",
        "actor": "SP_RDV_000"
    },
...
    "new_spawn_points": [
        {
            "new_actor": {
                "actor": "SP_RDV_000",
                "scenario": "s070_basesanc"
            },
            "location": {
                "x": -3344.789579158317,
                "y": -6255.911823647295,
                "z": 0.0
            }
        }
    ],
```

**Review by duncathan — CHANGES_REQUESTED** [review]
Any time we're adding actors, we should be sure to add them to actor groups. I *think* if we don't do that, they get placed in a global "orphans" group and they'll be loaded at all times - this is a useful fallback but it's irresponsible for us to depend on it. I whipped this up but didn't test it, a function to add to `Brfld`:
```py
def add_actor_to_collision_camera_groups(self, collision_camera_name: str, actor_name: str, layer_name: str = "default"):
        collision_camera_groups = [group for group in self.all_actor_groups() if group.startswith(collision_camera_name)]
        for group in collision_camera_groups:
            self.add_actor_to_group(group, actor_name, layer_name)
```

I'd suggest using something like this to add the new actor to all of the actor groups for its collision camera. The name of the collision camera can be passed in the patcher json (the database already has all of these)

**Review by henriquegemignani — CHANGES_REQUESTED** [review]
Add an use of this feature to `test/test_files/starter_preset_patcher.json`.
Please also update the required meds version in setup.cfg to 0.19.0.

**Comment by ThanatosGit** [comment]
> Add an use of this feature to `test/test_files/starter_preset_patcher.json`. Please also update the required meds version in setup.cfg to 0.19.0.

Changed and updated the branch

**Review by henriquegemignani — APPROVED** [review]

**Pull request merged**
